[project]
name = "hw1"
version = "0.1.0"
description = "Repository for first homework of course"
authors = ["Anton Shiryaev <med.phisiker@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.2,<3.13"
click = ">=8.1.7,<8.2"
